In [1]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [3]:
movies = pd.read_csv('Movie+Assignment+Data.csv')
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
# Write your code for inspection here
print(movies.head())
print(movies.shape)
print(movies.dtypes)

   color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0
1  Color     Gore Verbinski                   302.0     169.0
2  Color         Sam Mendes                   602.0     148.0
3  Color  Christopher Nolan                   813.0     164.0
4    NaN        Doug Walker                     NaN       NaN

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore
1                    563.0                  1000.0     Orlando Bloom
2                      0.0                   161.0      Rory Kinnear
3                  22000.0                 23000.0    Christian Bale
4                    131.0                     NaN        Rob Walker

   actor_1_facebook_likes        gross                           genres  ...  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi  ...
1                 40000.0  309404152.0         Action|Adventure|Fantasy  ...
2                 11000.0  200074175.0        Action|Adventure|Thriller  ...
3                 27000.0  448130642.0                  Action|Thriller  ...
4                   131.0          NaN                      Documentary  ...

  num_user_for_reviews language  country  content_rating       budget  \
0               3054.0  English      USA           PG-13  237000000.0
1               1238.0  English      USA           PG-13  300000000.0
2                994.0  English       UK           PG-13  245000000.0
3               2701.0  English      USA           PG-13  250000000.0
4                  NaN      NaN      NaN             NaN          NaN

   title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0      2009.0                  936.0        7.9          1.78
1      2007.0                 5000.0        7.1          2.35
2      2015.0                  393.0        6.8          2.35
3      2012.0                23000.0        8.5          2.35
4         NaN                   12.0        7.1           NaN

  movie_facebook_likes
0                33000
1                    0
2                85000
3               164000
4                    0

[5 rows x 28 columns]
(5043, 28)
color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [5]:
print(movies.isnull().sum())

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [7]:
# Write your code for row-wise null count here
print(movies.apply(lambda x: x.count(),axis=1))

0       28
1       28
2       28
3       28
4       14
        ..
5038    24
5039    23
5040    24
5041    26
5042    28
Length: 5043, dtype: int64

In [6]:
# Write your code for column-wise null percentages here
pc=movies.isnull().sum()*100/len(movies)
print(round(pc,2))

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [7]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
dt=movies.drop(['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link','aspect_ratio','plot_keywords'],axis=1)
dt.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [8]:
# Write your code for dropping the rows here
dt = dt[~np.isnan(dt['gross'])]
dt = dt[~np.isnan(dt['budget'])]
dt.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [10]:
# Write your code for dropping the rows here
dt=dt[dt.isnull().sum(axis=1)<=5]

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [11]:
# Write your code for filling the NaN values in the 'language' column here
dt.loc[pd.isnull(dt['language']), ['language']] = 'English'

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [9]:
# Write your code for checking number of retained rows here
print(dt.index)

Int64Index([   0,    1,    2,    3,    5,    6,    7,    8,    9,   10,
            ...
            5023, 5025, 5026, 5027, 5029, 5033, 5034, 5035, 5037, 5042],
           dtype='int64', length=3891)

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [10]:
# Write your code for unit conversion here
dt[['gross','budget']].apply(lambda x:x/1000000)

           gross    budget
0     760.505847  237.0000
1     309.404152  300.0000
2     200.074175  245.0000
3     448.130642  250.0000
5      73.058679  263.7000
...          ...       ...
5033    0.424760    0.0070
5034    0.070071    0.0070
5035    2.040920    0.0070
5037    0.004584    0.0090
5042    0.085222    0.0011

[3891 rows x 2 columns]

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [11]:
# Write your code for creating the profit column here
dt['profit']=dt['gross']-dt['budget']
dt

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,523505847.0
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0,9404152.0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000,-44925825.0
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000,198130642.0
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000,-190641321.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000,417760.0
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74,63071.0
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0,2033920.0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413,-4416.0
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456,84122.0

In [12]:
# Write your code for sorting the dataframe here
dt.sort_values(by='profit',ascending=True)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
2988,Joon-ho Bong,363.0,2201412.0,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,1.221550e+10,2006.0,7.0,7000,-1.221330e+10
3859,Chan-wook Park,202.0,211667.0,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4.200000e+09,2005.0,7.7,4000,-4.199788e+09
3005,Lajos Koltai,73.0,195888.0,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2.500000e+09,2005.0,7.1,607,-2.499804e+09
2323,Hayao Miyazaki,174.0,2298191.0,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2.400000e+09,1997.0,8.4,11000,-2.397702e+09
2334,Katsuhiro Ôtomo,105.0,410388.0,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2.127520e+09,2004.0,6.9,973,-2.127110e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3080,Steven Spielberg,215.0,434949459.0,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,1.050000e+07,1982.0,7.9,34000,4.244495e+08
3024,George Lucas,282.0,460935665.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,1.100000e+07,1977.0,8.7,33000,4.499357e+08
26,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,2.000000e+08,1997.0,7.7,26000,4.586723e+08
29,Colin Trevorrow,644.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,1.500000e+08,2015.0,7.0,150000,5.021773e+08
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,2.370000e+08,2009.0,7.9,33000,5.235058e+08

In [13]:
top10 = dt.sort_values(by='profit',ascending=False).head(10)
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,523505847.0
29,Colin Trevorrow,644.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150000000.0,2015.0,7.0,150000,502177271.0
26,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,458672302.0
3024,George Lucas,282.0,460935665.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11000000.0,1977.0,8.7,33000,449935665.0
3080,Steven Spielberg,215.0,434949459.0,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10500000.0,1982.0,7.9,34000,424449459.0
794,Joss Whedon,703.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220000000.0,2012.0,8.1,123000,403279547.0
17,Joss Whedon,703.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220000000.0,2012.0,8.1,123000,403279547.0
509,Roger Allers,186.0,422783777.0,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45000000.0,1994.0,8.5,17000,377783777.0
240,George Lucas,320.0,474544677.0,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115000000.0,1999.0,6.5,13000,359544677.0
66,Christopher Nolan,645.0,533316061.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185000000.0,2008.0,9.0,37000,348316061.0

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [14]:
# Write your code for dropping duplicate values here
dt.drop_duplicates()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,523505847.0
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0,9404152.0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000,-44925825.0
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000,198130642.0
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000,-190641321.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000,417760.0
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74,63071.0
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0,2033920.0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413,-4416.0
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456,84122.0

In [15]:
# Write code for repeating subtask 2 here
top10=dt.sort_values(by='profit',ascending=False).head(10)
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,523505847.0
29,Colin Trevorrow,644.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150000000.0,2015.0,7.0,150000,502177271.0
26,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,458672302.0
3024,George Lucas,282.0,460935665.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11000000.0,1977.0,8.7,33000,449935665.0
3080,Steven Spielberg,215.0,434949459.0,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10500000.0,1982.0,7.9,34000,424449459.0
794,Joss Whedon,703.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220000000.0,2012.0,8.1,123000,403279547.0
17,Joss Whedon,703.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220000000.0,2012.0,8.1,123000,403279547.0
509,Roger Allers,186.0,422783777.0,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45000000.0,1994.0,8.5,17000,377783777.0
240,George Lucas,320.0,474544677.0,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115000000.0,1999.0,6.5,13000,359544677.0
66,Christopher Nolan,645.0,533316061.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185000000.0,2008.0,9.0,37000,348316061.0

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [21]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
IMDb_Top_250= dt.sort_values(by=['imdb_score'],ascending=False).head(250)
IMDb_Top_250.loc[(IMDb_Top_250.num_voted_users>25),:]
IMDb_Top_250['Rank']=range(1,251)
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
1937,Frank Darabont,199.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25000000.0,1994.0,9.3,108000,3341469.0,1
3466,Francis Ford Coppola,208.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6000000.0,1972.0,9.2,43000,128821952.0,2
66,Christopher Nolan,645.0,533316061.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185000000.0,2008.0,9.0,37000,348316061.0,3
2837,Francis Ford Coppola,149.0,57300000.0,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13000000.0,1974.0,9.0,14000,44300000.0,4
3355,Quentin Tarantino,215.0,107930000.0,Crime|Drama,Bruce Willis,Pulp Fiction,1324680,2195.0,English,8000000.0,1994.0,8.9,45000,99930000.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1606,Nick Cassavetes,177.0,64286.0,Drama|Romance,Ryan Gosling,The Notebook,396396,1111.0,English,29000000.0,2004.0,7.9,57000,-28935714.0,246
89,Don Hall,384.0,222487711.0,Action|Adventure|Animation|Comedy|Drama|Family...,Damon Wayans Jr.,Big Hero 6,279093,433.0,English,165000000.0,2014.0,7.9,41000,57487711.0,247
1884,Brian De Palma,123.0,76270454.0,Crime|Drama|Thriller,Robert De Niro,The Untouchables,219008,418.0,English,25000000.0,1987.0,7.9,0,51270454.0,248
1748,F. Gary Gray,349.0,161029270.0,Biography|Crime|Drama|History|Music,Aldis Hodge,Straight Outta Compton,119928,331.0,English,28000000.0,2015.0,7.9,76000,133029270.0,249
99,Peter Jackson,645.0,303001229.0,Adventure|Fantasy,Aidan Turner,The Hobbit: An Unexpected Journey,637246,1367.0,English,180000000.0,2012.0,7.9,166000,123001229.0,250

In [22]:
Top_Foreign_Lang_Film = IMDb_Top_250.loc[(IMDb_Top_250.language != 'English'),:] 
Top_Foreign_Lang_Film

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
4498,Sergio Leone,181.0,6100000.0,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000e+06,1966.0,8.9,20000,4.900000e+06,7
4029,Fernando Meirelles,214.0,7563397.0,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.300000e+06,2002.0,8.7,28000,4.263397e+06,15
4747,Akira Kurosawa,153.0,269061.0,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.000000e+06,1954.0,8.7,11000,-1.730939e+06,16
2373,Hayao Miyazaki,246.0,10049886.0,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,1.900000e+07,2001.0,8.6,28000,-8.950114e+06,23
4259,Florian Henckel von Donnersmarck,215.0,11284657.0,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.000000e+06,2006.0,8.5,39000,9.284657e+06,31
4921,Majid Majidi,46.0,925402.0,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,1.800000e+05,1997.0,8.5,0,7.454020e+05,43
3931,Ron Fricke,115.0,2601847.0,Documentary|Music,Collin Alfredo St. Dic,Samsara,22457,69.0,None,4.000000e+06,2011.0,8.5,26000,-1.398153e+06,45
4105,Chan-wook Park,305.0,2181290.0,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.000000e+06,2003.0,8.4,43000,-8.187100e+05,50
2323,Hayao Miyazaki,174.0,2298191.0,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2.400000e+09,1997.0,8.4,11000,-2.397702e+09,51
1298,Jean-Pierre Jeunet,242.0,33201661.0,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,7.700000e+07,2001.0,8.4,39000,-4.379834e+07,54
2970,Wolfgang Petersen,96.0,11433134.0,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,1.400000e+07,1981.0,8.4,11000,-2.566866e+06,56
1329,S.S. Rajamouli,44.0,6498000.0,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,1.802615e+07,2015.0,8.4,21000,-1.152815e+07,57
4659,Asghar Farhadi,354.0,7098492.0,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,5.000000e+05,2011.0,8.4,48000,6.598492e+06,63
2829,Oliver Hirschbiegel,192.0,5501940.0,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,1.350000e+07,2004.0,8.3,14000,-7.998060e+06,76
2734,Fritz Lang,260.0,26435.0,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.000000e+06,1927.0,8.3,12000,-5.973565e+06,85
4033,Thomas Vinterberg,349.0,610968.0,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.800000e+06,2012.0,8.3,60000,-3.189032e+06,89
3550,Denis Villeneuve,226.0,6857096.0,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.800000e+06,2010.0,8.2,37000,5.709600e+04,92
4585,Joshua Oppenheimer,248.0,484221.0,Biography|Crime|Documentary|History,Anwar Congo,The Act of Killing,23836,107.0,Indonesian,1.000000e+06,2012.0,8.2,20000,-5.157790e+05,104
2047,Hayao Miyazaki,212.0,4710455.0,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,2.400000e+07,2004.0,8.2,13000,-1.928954e+07,109
2551,Guillermo del Toro,406.0,37623143.0,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,1.350000e+07,2006.0,8.2,27000,2.412314e+07,111
4000,Juan José Campanella,262.0,20167424.0,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,2.000000e+06,2009.0,8.2,33000,1.816742e+07,113
4461,Thomas Vinterberg,98.0,1647780.0,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.300000e+06,1998.0,8.1,5000,3.477800e+05,117
3423,Katsuhiro Ôtomo,150.0,439162.0,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1.100000e+09,1988.0,8.1,0,-1.099561e+09,129
2830,Alejandro Amenábar,157.0,2086345.0,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,1.000000e+07,2004.0,8.1,0,-7.913655e+06,131
2914,Je-kyu Kang,86.0,1110186.0,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,1.280000e+07,2004.0,8.1,0,-1.168981e+07,133
4267,Alejandro G. Iñárritu,157.0,5383834.0,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.000000e+06,2000.0,8.1,11000,3.383834e+06,144
3553,José Padilha,142.0,8060.0,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.000000e+06,2007.0,8.1,11000,-3.991940e+06,152
3456,Vincent Paronnaud,242.0,4443403.0,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.300000e+06,2007.0,8.0,14000,-2.856597e+06,184
4897,Sergio Leone,122.0,3500000.0,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,2.000000e+05,1964.0,8.0,0,3.300000e+06,194
4284,Ari Folman,231.0,2283276.0,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.500000e+06,2008.0,8.0,0,7.832760e+05,201
3344,Karan Johar,210.0,4018695.0,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,1.200000e+07,2010.0,8.0,27000,-7.981305e+06,212
4144,Walter Salles,71.0,5595428.0,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.900000e+06,1998.0,8.0,0,2.695428e+06,217
2919,Stéphane Aubier,99.0,71442.0,Animation|Comedy|Crime|Drama|Family,Mackenzie Foy,Ernest & Celestine,12029,32.0,French,9.600000e+06,2012.0,7.9,0,-9.528558e+06,222
1171,Yimou Zhang,283.0,84961.0,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,3.100000e+07,2002.0,7.9,0,-3.091504e+07,224
3264,Michael Haneke,447.0,225377.0,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.900000e+06,2012.0,7.9,33000,-8.674623e+06,229
4499,Anna Muylaert,111.0,375723.0,Comedy|Drama,Alex Huszar,The Second Mother,7025,26.0,Portuguese,4.000000e+06,2015.0,7.9,0,-3.624277e+06,230
4415,Fabián Bielinsky,94.0,1221261.0,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215,125.0,Spanish,1.500000e+06,2000.0,7.9,0,-2.787390e+05,236
3510,Yash Chopra,29.0,2921738.0,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.000000e+06,2004.0,7.9,2000,-4.078262e+06,237
3677,Christophe Barratier,112.0,3629758.0,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.500000e+06,2004.0,7.9,0,-1.870242e+06,240

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [23]:
# Write your code for extracting the top 10 directors here

top10director=dt.groupby('director_name')['imdb_score'].mean().sort_values(ascending=False).head(10)
top10director

director_name
Charles Chaplin          8.600000
Tony Kaye                8.600000
Damien Chazelle          8.500000
Ron Fricke               8.500000
Alfred Hitchcock         8.500000
Majid Majidi             8.500000
Sergio Leone             8.433333
Christopher Nolan        8.425000
Marius A. Markevicius    8.400000
S.S. Rajamouli           8.400000
Name: imdb_score, dtype: float64

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [26]:
# Write your code for extracting the first two genres of each movie here
first_two=dt['genres'].apply(lambda x: pd.Series(x.split('|')))
dt['genre_1']=first_two[0]
dt['genre_2']=first_two[1]
dt['genre_2'].fillna(dt['genre_1'],inplace=True)
print(dt.genre_1)
print(dt.genre_2)

0            Action
1            Action
2            Action
3            Action
5            Action
           ...
5033          Drama
5034       Thriller
5035         Action
5037         Comedy
5042    Documentary
Name: genre_1, Length: 3891, dtype: object
0         Adventure
1         Adventure
2         Adventure
3          Thriller
5         Adventure
           ...
5033         Sci-Fi
5034       Thriller
5035          Crime
5037          Drama
5042    Documentary
Name: genre_2, Length: 3891, dtype: object

In [28]:
movies_by_segment = dt.groupby(['genre_1','genre_2'])
movies_by_segment

In [32]:
PopGenre = movies_by_segment['gross'].mean().sort_values(ascending=False).head(5)
PopGenre

genre_1    genre_2
Family     Sci-Fi       4.349495e+08
Adventure  Sci-Fi       2.286278e+08
           Animation    1.169985e+08
           Family       1.165208e+08
Action     Adventure    1.103825e+08
Name: gross, dtype: float64

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [35]:
# Write your code for creating three new dataframes here

Meryl_Streep = Meryl_Streep=dt.loc[(dt.actor_1_name=='Meryl Streep'),:].head(3891)
Meryl_Streep

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
410,Color,Nancy Meyers,187.0,120.0,278.0,963.0,Hunter Parrish,11000.0,112703470.0,Comedy|Drama|Romance,...,214.0,English,USA,R,85000000.0,2009.0,2000.0,6.6,1.85,0
1106,Color,Curtis Hanson,42.0,111.0,161.0,132.0,Glenn Morshower,11000.0,46815748.0,Action|Adventure|Crime|Thriller,...,69.0,English,USA,PG-13,45000000.0,1994.0,894.0,6.3,2.35,0
1204,Color,Nora Ephron,252.0,123.0,0.0,923.0,Mary Lynn Rajskub,11000.0,94125426.0,Biography|Drama|Romance,...,277.0,English,USA,PG-13,40000000.0,2009.0,935.0,7.0,1.85,13000
1408,Color,David Frankel,208.0,109.0,64.0,505.0,Anne Hathaway,11000.0,124732962.0,Comedy|Drama|Romance,...,631.0,English,USA,PG-13,35000000.0,2006.0,11000.0,6.8,2.35,0
1483,Color,Robert Redford,227.0,92.0,0.0,10000.0,Tom Cruise,11000.0,14998070.0,Drama|Thriller|War,...,298.0,English,USA,R,35000000.0,2007.0,10000.0,6.2,2.35,0
1575,Color,Sydney Pollack,66.0,161.0,521.0,184.0,Michael Gough,11000.0,87100000.0,Biography|Drama|Romance,...,200.0,English,USA,PG,31000000.0,1985.0,920.0,7.2,1.85,0
1618,Color,David Frankel,234.0,100.0,64.0,329.0,Steve Carell,11000.0,63536011.0,Comedy|Drama|Romance,...,178.0,English,USA,PG-13,30000000.0,2012.0,7000.0,6.3,2.35,0
1674,Color,Carl Franklin,64.0,127.0,73.0,433.0,William Hurt,11000.0,23209440.0,Drama,...,112.0,English,USA,R,30000000.0,1998.0,882.0,7.0,1.85,592
1752,Color,Stephen Frears,87.0,110.0,350.0,83.0,Nina Arianda,11000.0,NaN,Biography|Comedy|Drama|Music|Romance,...,32.0,English,UK,PG-13,29000000.0,2016.0,183.0,7.1,2.35,0
1925,Color,Stephen Daldry,174.0,114.0,335.0,530.0,Stephen Dillane,11000.0,41597830.0,Drama|Romance,...,660.0,English,USA,PG-13,25000000.0,2002.0,577.0,7.6,1.85,0
2781,Color,Phyllida Lloyd,331.0,105.0,58.0,583.0,Jim Broadbent,11000.0,29959436.0,Biography|Drama|History,...,350.0,English,UK,PG-13,13000000.0,2011.0,1000.0,6.4,2.35,18000
3135,Color,Robert Altman,211.0,105.0,500.0,718.0,Virginia Madsen,11000.0,20338609.0,Comedy|Drama|Music,...,280.0,English,USA,PG-13,10000000.0,2006.0,912.0,6.8,2.35,683
3641,Color,Fred Zinnemann,38.0,117.0,160.0,898.0,Jane Fonda,11000.0,NaN,Drama,...,44.0,English,USA,PG,7840000.0,1977.0,949.0,7.4,1.85,733

In [36]:
Leo_Caprio = Leo_Caprio=dt.loc[(dt.actor_1_name=='Leonardo DiCaprio'),:].head(3891)
Leo_Caprio

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
50,Color,Baz Luhrmann,490.0,143.0,1000.0,77.0,Elizabeth Debicki,29000.0,144812796.0,Drama|Romance,...,753.0,English,Australia,PG-13,105000000.0,2013.0,509.0,7.3,2.35,115000
97,Color,Christopher Nolan,642.0,148.0,22000.0,23000.0,Tom Hardy,29000.0,292568851.0,Action|Adventure|Sci-Fi|Thriller,...,2803.0,English,USA,PG-13,160000000.0,2010.0,27000.0,8.8,2.35,175000
179,Color,Alejandro G. Iñárritu,556.0,156.0,0.0,733.0,Tom Hardy,29000.0,183635922.0,Adventure|Drama|Thriller|Western,...,1188.0,English,USA,R,135000000.0,2015.0,27000.0,8.1,2.35,190000
257,Black and White,Martin Scorsese,267.0,170.0,17000.0,827.0,Adam Scott,29000.0,102608827.0,Biography|Drama,...,799.0,English,USA,PG-13,110000000.0,2004.0,3000.0,7.5,2.35,0
296,Color,Quentin Tarantino,765.0,165.0,16000.0,265.0,Christoph Waltz,29000.0,162804648.0,Drama|Western,...,1193.0,English,USA,R,100000000.0,2012.0,11000.0,8.5,2.35,199000
307,Color,Edward Zwick,166.0,143.0,380.0,452.0,Djimon Hounsou,29000.0,57366262.0,Adventure|Drama|Thriller,...,657.0,English,Germany,R,100000000.0,2006.0,3000.0,8.0,2.35,14000
308,Color,Martin Scorsese,606.0,240.0,17000.0,4000.0,Matthew McConaughey,29000.0,116866727.0,Biography|Comedy|Crime|Drama,...,1138.0,English,USA,R,100000000.0,2013.0,11000.0,8.2,2.35,138000
326,Color,Martin Scorsese,233.0,216.0,17000.0,1000.0,Liam Neeson,29000.0,77679638.0,Crime|Drama,...,1166.0,English,USA,R,100000000.0,2002.0,14000.0,7.5,2.35,0
361,Color,Martin Scorsese,352.0,151.0,17000.0,1000.0,Matt Damon,29000.0,132373442.0,Crime|Drama|Thriller,...,2054.0,English,USA,R,90000000.0,2006.0,13000.0,8.5,2.35,29000
452,Color,Martin Scorsese,490.0,138.0,17000.0,163.0,Joseph Sikora,29000.0,127968405.0,Mystery|Thriller,...,964.0,English,USA,R,80000000.0,2010.0,223.0,8.1,2.35,53000
641,Color,Ridley Scott,238.0,128.0,0.0,135.0,Simon McBurney,29000.0,39380442.0,Action|Drama|Thriller,...,263.0,English,USA,R,70000000.0,2008.0,149.0,7.1,2.35,0
911,Color,Steven Spielberg,194.0,141.0,14000.0,3000.0,Tom Hanks,29000.0,164435221.0,Biography|Crime|Drama,...,667.0,English,USA,PG-13,52000000.0,2002.0,15000.0,8.0,1.85,15000
990,Color,Danny Boyle,118.0,119.0,0.0,39.0,Virginie Ledoyen,29000.0,39778599.0,Adventure|Drama|Thriller,...,548.0,English,USA,R,50000000.0,2000.0,414.0,6.6,2.35,0
1114,Color,Sam Mendes,323.0,119.0,0.0,10000.0,Kate Winslet,29000.0,22877808.0,Drama|Romance,...,414.0,English,USA,R,35000000.0,2008.0,14000.0,7.3,2.35,0
1422,Color,Randall Wallace,83.0,132.0,130.0,80.0,Anne Parillaud,29000.0,56876365.0,Action|Adventure,...,244.0,English,USA,PG-13,35000000.0,1998.0,130.0,6.4,1.85,0
1453,Color,Clint Eastwood,392.0,137.0,16000.0,363.0,Naomi Watts,29000.0,37304950.0,Biography|Crime|Drama,...,279.0,English,USA,R,35000000.0,2011.0,6000.0,6.6,2.35,16000
1560,Black and White,Sam Raimi,63.0,107.0,0.0,159.0,Pat Hingle,29000.0,18636537.0,Action|Thriller|Western,...,216.0,English,Japan,R,32000000.0,1995.0,165.0,6.4,1.85,0
2067,Color,Jerry Zaks,45.0,98.0,4.0,11000.0,Robert De Niro,29000.0,12782508.0,Drama,...,71.0,English,USA,PG-13,23000000.0,1996.0,22000.0,6.7,1.85,1000
2757,Color,Baz Luhrmann,106.0,120.0,1000.0,954.0,Harold Perrineau,29000.0,46338728.0,Drama|Romance,...,506.0,English,USA,PG-13,14500000.0,1996.0,1000.0,6.8,2.35,10000
3476,Color,Baz Luhrmann,490.0,143.0,1000.0,76.0,Elizabeth Debicki,29000.0,144812796.0,Drama|Romance,...,753.0,English,Australia,PG-13,105000000.0,2013.0,509.0,7.3,2.35,115000

In [39]:
Brad_Pitt = Brad_Pitt=dt.loc[(dt.actor_1_name=='Brad Pitt'),:].head(3891)
Brad_Pitt

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
101,David Fincher,362.0,127490802.0,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150000000.0,2008.0,7.8,23000,-22509198.0,Drama,Fantasy
147,Wolfgang Petersen,220.0,133228348.0,Adventure,Brad Pitt,Troy,381672,1694.0,English,175000000.0,2004.0,7.2,0,-41771652.0,Adventure,Adventure
254,Steven Soderbergh,198.0,125531634.0,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110000000.0,2004.0,6.4,0,15531634.0,Crime,Thriller
255,Doug Liman,233.0,186336103.0,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120000000.0,2005.0,6.5,0,66336103.0,Action,Comedy
382,Tony Scott,142.0,26871.0,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92000000.0,2001.0,7.0,0,-91973129.0,Action,Crime
400,Steven Soderbergh,186.0,183405771.0,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85000000.0,2001.0,7.8,0,98405771.0,Crime,Thriller
470,David Ayer,406.0,85707116.0,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68000000.0,2014.0,7.6,82000,17707116.0,Action,Drama
611,Jean-Jacques Annaud,76.0,37901509.0,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70000000.0,1997.0,7.0,0,-32098491.0,Adventure,Biography
683,David Fincher,315.0,37023395.0,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63000000.0,1999.0,8.8,48000,-25976605.0,Drama,Drama
792,Patrick Gilmore,98.0,26288320.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60000000.0,2003.0,6.7,880,-33711680.0,Adventure,Animation
940,Neil Jordan,120.0,105264608.0,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60000000.0,1994.0,7.6,11000,45264608.0,Drama,Fantasy
1490,Terrence Malick,584.0,13303319.0,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32000000.0,2011.0,6.7,39000,-18696681.0,Drama,Fantasy
1722,Andrew Dominik,273.0,3904982.0,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30000000.0,2007.0,7.5,0,-26095018.0,Biography,Crime
2204,Alejandro G. Iñárritu,285.0,34300771.0,Drama,Brad Pitt,Babel,243799,908.0,English,25000000.0,2006.0,7.5,0,9300771.0,Drama,Drama
2333,Angelina Jolie Pitt,131.0,531009.0,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10000000.0,2015.0,5.3,0,-9468991.0,Drama,Romance
2682,Andrew Dominik,414.0,14938570.0,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15000000.0,2012.0,6.2,20000,-61430.0,Crime,Thriller
2898,Tony Scott,122.0,12281500.0,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13000000.0,1993.0,8.0,15000,-718500.0,Action,Crime

In [40]:
# Write your code for combining the three dataframes here
Combined_df=Meryl_Streep.append(Leo_Caprio).append(Brad_Pitt)
Combined_df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,profit,genre_1,genre_2
410,Color,Nancy Meyers,187.0,120.0,278.0,963.0,Hunter Parrish,11000.0,112703470.0,Comedy|Drama|Romance,...,R,85000000.0,2009.0,2000.0,6.6,1.85,0,NaN,NaN,NaN
1106,Color,Curtis Hanson,42.0,111.0,161.0,132.0,Glenn Morshower,11000.0,46815748.0,Action|Adventure|Crime|Thriller,...,PG-13,45000000.0,1994.0,894.0,6.3,2.35,0,NaN,NaN,NaN
1204,Color,Nora Ephron,252.0,123.0,0.0,923.0,Mary Lynn Rajskub,11000.0,94125426.0,Biography|Drama|Romance,...,PG-13,40000000.0,2009.0,935.0,7.0,1.85,13000,NaN,NaN,NaN
1408,Color,David Frankel,208.0,109.0,64.0,505.0,Anne Hathaway,11000.0,124732962.0,Comedy|Drama|Romance,...,PG-13,35000000.0,2006.0,11000.0,6.8,2.35,0,NaN,NaN,NaN
1483,Color,Robert Redford,227.0,92.0,0.0,10000.0,Tom Cruise,11000.0,14998070.0,Drama|Thriller|War,...,R,35000000.0,2007.0,10000.0,6.2,2.35,0,NaN,NaN,NaN
1575,Color,Sydney Pollack,66.0,161.0,521.0,184.0,Michael Gough,11000.0,87100000.0,Biography|Drama|Romance,...,PG,31000000.0,1985.0,920.0,7.2,1.85,0,NaN,NaN,NaN
1618,Color,David Frankel,234.0,100.0,64.0,329.0,Steve Carell,11000.0,63536011.0,Comedy|Drama|Romance,...,PG-13,30000000.0,2012.0,7000.0,6.3,2.35,0,NaN,NaN,NaN
1674,Color,Carl Franklin,64.0,127.0,73.0,433.0,William Hurt,11000.0,23209440.0,Drama,...,R,30000000.0,1998.0,882.0,7.0,1.85,592,NaN,NaN,NaN
1752,Color,Stephen Frears,87.0,110.0,350.0,83.0,Nina Arianda,11000.0,NaN,Biography|Comedy|Drama|Music|Romance,...,PG-13,29000000.0,2016.0,183.0,7.1,2.35,0,NaN,NaN,NaN
1925,Color,Stephen Daldry,174.0,114.0,335.0,530.0,Stephen Dillane,11000.0,41597830.0,Drama|Romance,...,PG-13,25000000.0,2002.0,577.0,7.6,1.85,0,NaN,NaN,NaN
2781,Color,Phyllida Lloyd,331.0,105.0,58.0,583.0,Jim Broadbent,11000.0,29959436.0,Biography|Drama|History,...,PG-13,13000000.0,2011.0,1000.0,6.4,2.35,18000,NaN,NaN,NaN
3135,Color,Robert Altman,211.0,105.0,500.0,718.0,Virginia Madsen,11000.0,20338609.0,Comedy|Drama|Music,...,PG-13,10000000.0,2006.0,912.0,6.8,2.35,683,NaN,NaN,NaN
3641,Color,Fred Zinnemann,38.0,117.0,160.0,898.0,Jane Fonda,11000.0,NaN,Drama,...,PG,7840000.0,1977.0,949.0,7.4,1.85,733,NaN,NaN,NaN
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000,NaN,NaN,NaN
50,Color,Baz Luhrmann,490.0,143.0,1000.0,77.0,Elizabeth Debicki,29000.0,144812796.0,Drama|Romance,...,PG-13,105000000.0,2013.0,509.0,7.3,2.35,115000,NaN,NaN,NaN
97,Color,Christopher Nolan,642.0,148.0,22000.0,23000.0,Tom Hardy,29000.0,292568851.0,Action|Adventure|Sci-Fi|Thriller,...,PG-13,160000000.0,2010.0,27000.0,8.8,2.35,175000,NaN,NaN,NaN
179,Color,Alejandro G. Iñárritu,556.0,156.0,0.0,733.0,Tom Hardy,29000.0,183635922.0,Adventure|Drama|Thriller|Western,...,R,135000000.0,2015.0,27000.0,8.1,2.35,190000,NaN,NaN,NaN
257,Black and White,Martin Scorsese,267.0,170.0,17000.0,827.0,Adam Scott,29000.0,102608827.0,Biography|Drama,...,PG-13,110000000.0,2004.0,3000.0,7.5,2.35,0,NaN,NaN,NaN
296,Color,Quentin Tarantino,765.0,165.0,16000.0,265.0,Christoph Waltz,29000.0,162804648.0,Drama|Western,...,R,100000000.0,2012.0,11000.0,8.5,2.35,199000,NaN,NaN,NaN
307,Color,Edward Zwick,166.0,143.0,380.0,452.0,Djimon Hounsou,29000.0,57366262.0,Adventure|Drama|Thriller,...,R,100000000.0,2006.0,3000.0,8.0,2.35,14000,NaN,NaN,NaN
308,Color,Martin Scorsese,606.0,240.0,17000.0,4000.0,Matthew McConaughey,29000.0,116866727.0,Biography|Comedy|Crime|Drama,...,R,100000000.0,2013.0,11000.0,8.2,2.35,138000,NaN,NaN,NaN
326,Color,Martin Scorsese,233.0,216.0,17000.0,1000.0,Liam Neeson,29000.0,77679638.0,Crime|Drama,...,R,100000000.0,2002.0,14000.0,7.5,2.35,0,NaN,NaN,NaN
361,Color,Martin Scorsese,352.0,151.0,17000.0,1000.0,Matt Damon,29000.0,132373442.0,Crime|Drama|Thriller,...,R,90000000.0,2006.0,13000.0,8.5,2.35,29000,NaN,NaN,NaN
452,Color,Martin Scorsese,490.0,138.0,17000.0,163.0,Joseph Sikora,29000.0,127968405.0,Mystery|Thriller,...,R,80000000.0,2010.0,223.0,8.1,2.35,53000,NaN,NaN,NaN
641,Color,Ridley Scott,238.0,128.0,0.0,135.0,Simon McBurney,29000.0,39380442.0,Action|Drama|Thriller,...,R,70000000.0,2008.0,149.0,7.1,2.35,0,NaN,NaN,NaN
911,Color,Steven Spielberg,194.0,141.0,14000.0,3000.0,Tom Hanks,29000.0,164435221.0,Biography|Crime|Drama,...,PG-13,52000000.0,2002.0,15000.0,8.0,1.85,15000,NaN,NaN,NaN
990,Color,Danny Boyle,118.0,119.0,0.0,39.0,Virginie Ledoyen,29000.0,39778599.0,Adventure|Drama|Thriller,...,R,50000000.0,2000.0,414.0,6.6,2.35,0,NaN,NaN,NaN
1114,Color,Sam Mendes,323.0,119.0,0.0,10000.0,Kate Winslet,29000.0,22877808.0,Drama|Romance,...,R,35000000.0,2008.0,14000.0,7.3,2.35,0,NaN,NaN,NaN
1422,Color,Randall Wallace,83.0,132.0,130.0,80.0,Anne Parillaud,29000.0,56876365.0,Action|Adventure,...,PG-13,35000000.0,1998.0,130.0,6.4,1.85,0,NaN,NaN,NaN
1453,Color,Clint Eastwood,392.0,137.0,16000.0,363.0,Naomi Watts,29000.0,37304950.0,Biography|Crime|Drama,...,R,35000000.0,2011.0,6000.0,6.6,2.35,16000,NaN,NaN,NaN
1560,Black and White,Sam Raimi,63.0,107.0,0.0,159.0,Pat Hingle,29000.0,18636537.0,Action|Thriller|Western,...,R,32000000.0,1995.0,165.0,6.4,1.85,0,NaN,NaN,NaN
2067,Color,Jerry Zaks,45.0,98.0,4.0,11000.0,Robert De Niro,29000.0,12782508.0,Drama,...,PG-13,23000000.0,1996.0,22000.0,6.7,1.85,1000,NaN,NaN,NaN
2757,Color,Baz Luhrmann,106.0,120.0,1000.0,954.0,Harold Perrineau,29000.0,46338728.0,Drama|Romance,...,PG-13,14500000.0,1996.0,1000.0,6.8,2.35,10000,NaN,NaN,NaN
3476,Color,Baz Luhrmann,490.0,143.0,1000.0,76.0,Elizabeth Debicki,29000.0,144812796.0,Drama|Romance,...,PG-13,105000000.0,2013.0,509.0,7.3,2.35,115000,NaN,NaN,NaN
101,NaN,David Fincher,362.0,NaN,NaN,NaN,NaN,NaN,127490802.0,Drama|Fantasy|Romance,...,NaN,150000000.0,2008.0,NaN,7.8,NaN,23000,-22509198.0,Drama,Fantasy
147,NaN,Wolfgang Petersen,220.0,NaN,NaN,NaN,NaN,NaN,133228348.0,Adventure,...,NaN,175000000.0,2004.0,NaN,7.2,NaN,0,-41771652.0,Adventure,Adventure
254,NaN,Steven Soderbergh,198.0,NaN,NaN,NaN,NaN,NaN,125531634.0,Crime|Thriller,...,NaN,110000000.0,2004.0,NaN,6.4,NaN,0,15531634.0,Crime,Thriller
255,NaN,Doug Liman,233.0,NaN,NaN,NaN,NaN,NaN,186336103.0,Action|Comedy|Crime|Romance|Thriller,...,NaN,120000000.0,2005.0,NaN,6.5,NaN,0,66336103.0,Action,Comedy
382,NaN,Tony Scott,142.0,NaN,NaN,NaN,NaN,NaN,26871.0,Action|Crime|Thriller,...,NaN,92000000.0,2001.0,NaN,7.0,NaN,0,-91973129.0,Action,Crime
400,NaN,Steven Soderbergh,186.0,NaN,NaN,NaN,NaN,NaN,183405771.0,Crime|Thriller,...,NaN,85000000.0,2001.0,NaN,7.8,NaN,0,98405771.0,Crime,Thriller
470,NaN,David Ayer,406.0,NaN,NaN,NaN,NaN,NaN,85707116.0,Action|Drama|War,...,NaN,68000000.0,2014.0,NaN,7.6,NaN,82000,17707116.0,Action,Drama
611,NaN,Jean-Jacques Annaud,76.0,NaN,NaN,NaN,NaN,NaN,37901509.0,Adventure|Biography|Drama|History|War,...,NaN,70000000.0,1997.0,NaN,7.0,NaN,0,-32098491.0,Adventure,Biography
683,NaN,David Fincher,315.0,NaN,NaN,NaN,NaN,NaN,37023395.0,Drama,...,NaN,63000000.0,1999.0,NaN,8.8,NaN,48000,-25976605.0,Drama,Drama
792,NaN,Patrick Gilmore,98.0,NaN,NaN,NaN,NaN,NaN,26288320.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,...,NaN,60000000.0,2003.0,NaN,6.7,NaN,880,-33711680.0,Adventure,Animation
940,NaN,Neil Jordan,120.0,NaN,NaN,NaN,NaN,NaN,105264608.0,Drama|Fantasy|Horror,...,NaN,60000000.0,1994.0,NaN,7.6,NaN,11000,45264608.0,Drama,Fantasy
1490,NaN,Terrence Malick,584.0,NaN,NaN,NaN,NaN,NaN,13303319.0,Drama|Fantasy,...,NaN,32000000.0,2011.0,NaN,6.7,NaN,39000,-18696681.0,Drama,Fantasy
1722,NaN,Andrew Dominik,273.0,NaN,NaN,NaN,NaN,NaN,3904982.0,Biography|Crime|Drama|History|Western,...,NaN,30000000.0,2007.0,NaN,7.5,NaN,0,-26095018.0,Biography,Crime
2204,NaN,Alejandro G. Iñárritu,285.0,NaN,NaN,NaN,NaN,NaN,34300771.0,Drama,...,NaN,25000000.0,2006.0,NaN,7.5,NaN,0,9300771.0,Drama,Drama
2333,NaN,Angelina Jolie Pitt,131.0,NaN,NaN,NaN,NaN,NaN,531009.0,Drama|Romance,...,NaN,10000000.0,2015.0,NaN,5.3,NaN,0,-9468991.0,Drama,Romance
2682,NaN,Andrew Dominik,414.0,NaN,NaN,NaN,NaN,NaN,14938570.0,Crime|Thriller,...,NaN,15000000.0,2012.0,NaN,6.2,NaN,20000,-61430.0,Crime,Thriller
2898,NaN,Tony Scott,122.0,NaN,NaN,NaN,NaN,NaN,12281500.0,Action|Crime|Drama|Romance|Thriller,...,NaN,13000000.0,1993.0,NaN,8.0,NaN,15000,-718500.0,Action,Crime

In [42]:
# Write your code for grouping the combined dataframe here
actor_name=Combined_df.groupby('actor_1_name')
actor_name

In [43]:
# Write the code for finding the mean of critic reviews and audience reviews here
critic_reviews=actor_name['num_critic_for_reviews'].mean().sort_values(ascending=False).head(49)
print(critic_reviews)
audience_reviews=actor_name['num_user_for_reviews'].mean().sort_values(ascending=False).head(49)
print(audience_reviews)

actor_1_name
Leonardo DiCaprio    330.190476
Brad Pitt            245.000000
Meryl Streep         163.153846
Name: num_critic_for_reviews, dtype: float64
actor_1_name
Leonardo DiCaprio    914.476190
Brad Pitt            742.352941
Meryl Streep         257.307692
Name: num_user_for_reviews, dtype: float64

**Checkpoint 6:** `Leonardo` has aced both the lists!